### PR TITLE
Ability to set UserID

### PR DESCRIPTION
**Pull request by ai-slave**
Really needed that for my project :)

### CODE REVIEW

**Comment by antony** [comment]
Hey there,

Thanks for this - the only issue is that you've edited a file called `generated-functions.js` which is a generated file. You have to add this function in the source so that it gets generated automatically :)

**Review by antony — CHANGES_REQUESTED** [review]
see pr details

**Comment by dextermb** [comment]
I don't think this would have ever worked as looking at the third parameter going into the queue would be `id` whereas it is expecting `data`.

**Comment by dextermb** [comment]
Implemented under #26. Although it will need testing as I just transplanted what was in this PR.

**Pull request closed without merging**
