### PR TITLE
Add function for setUserProperties

### PR DESCRIPTION
**Pull request by wishperhope**
I added function to set user properties like location or custom defined one, its useful when we need to split event by user properties on the google analytic dashboard.

See https://developers.google.com/analytics/devguides/collection/ga4/user-properties for reference docs.

### CODE REVIEW

**Comment by antony** [comment]
Looks good - could you include a section about it in the README too?

**Comment by wishperhope** [comment]
Oh, I am sorry I forget it.

**Comment by wishperhope** [comment]
I am sorry can it be merged ? or there anything else todo ? i already update the readme.

**Review by antony — APPROVED** [review]

**Comment by antony** [comment]
Hi There

I've just merged this into master - sorry it took so long.

I noticed a new function at the top of `generated-functions.js` - as the name implies, this file is auto-generated by a script, so anything you put in there will get wiped. Can you move those functions to another place so that they don't get wiped please :)

**Comment by wishperhope** [comment]
oh, i am sorry, sure i will move it to another place

**Pull request merged**
